development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://kboeelknzolutk:a3f5de9c659c67f9e5f51efb2dfea010e0685ba07dc6d88a55d2b04528e100eb@ec2-107-22-169-45.compute-1.amazonaws.com:5432/d4s839tiq764lg
  channel_prefix: myapp_production
